import React from "react";

const TC = () => {
  return (
    <div className="relative mt-10 md:w-3/5 w-[89%] my-9 m-auto">
      <div className="bg-orange-600 absolute -bottom-5 -right-5 w-[10rem] h-[10rem] -z-20" />
      <div className="bg-orange-600 absolute -left-5 -top-5 w-[10rem] h-[10rem] -z-20" />

      <div className=" *:block pl-10 py-6 min-h-[14rem] relative -z-10 shadow-md w-full bg-slate-100">
        <h1 className="text-orange-700 text-2xl mb-4">Terms And Conditons</h1>

        <div>
          <p>
            <span>{"*"}</span> These terms and conditions {"Terms"} govern your
            use of the product naming artificial intelligence {"AI"} service
            provided by <b>Namify</b>. By accessing or using the AI service, you
            agree to be bound by these Terms. If you do not agree with these
            Terms, you may not use the AI service.
          </p>
          <h3 className="text-xl font-bold my-4">Use of the AI Service</h3>
          <p>
            1.1. The AI service provided by the Namify.co is intended for
            generating Brand names and related Naming content based on user
            input.
          </p>
          <p>
            1.2. You must be of legal age and have the legal capacity to enter
            into these Terms. By using the AI service, you represent and warrant
            that you meet these requirements.
          </p>
          <p>
            1.3. You agree to use the AI service only for lawful purposes and in
            compliance with these Terms.
          </p>
          <h3 className="text-xl font-bold my-4">User Accounts </h3>{" "}
          <p>
            2.1. To access certain features of the AI service, you may be
            required to create a user account. You are responsible for
            maintaining the confidentiality of your account information and for
            all activities that occur under your account.
          </p>
          <p>
            2.2. The Company reserves the right to suspend or terminate your
            account if it believes that you have violated these Terms or engaged
            in unauthorized use of the AI service.
          </p>
          <h3 className="text-xl font-bold my-4">Intellectual Property </h3>
          <p>
            3.1. All intellectual property rights in the AI technology and
            generated content belong to the Company.
          </p>
          <p>
            3.2. You are granted a limited, non-exclusive, non-transferable
            license to use the naming suggestions generated by the AI for your
            own purposes.
          </p>
          <h3 className="text-xl font-bold my-4">Data Privacy</h3>{" "}
          <p>
            The Company collects and processes personal data in accordance with
            its Privacy Policy, available [link to Privacy Policy]. By using the
            AI service, you consent to the collection, storage, and use of your
            personal data as described in the Privacy Policy.{" "}
          </p>
          <h3 className="text-xl font-bold my-4"> Liability and Disclaimer</h3>{" "}
          <p>
            5.1. The AI service is provided on an "as is" and "as available"
            basis. The Company makes no warranties or representations regarding
            the accuracy, reliability, or suitability of the naming suggestions
            generated by the AI.
          </p>
          <p>
            5.2. The Company shall not be liable for any indirect, incidental,
            special, or consequential damages arising out of or in connection
            with your use of the AI service.{" "}
          </p>
          <h3 className="text-xl font-bold my-4"> Changes to Terms</h3>{" "}
          <p>
            The Company reserves the right to modify these Terms at any time.
            Any changes to these Terms will be effective immediately upon
            posting on the Company's website. Your continued use of the AI
            service after the posting of the revised Terms constitutes your
            acceptance of the changes.{" "}
          </p>
          <h3 className="text-xl font-bold my-4"> Contact Information </h3>
          <p>
            If you have any questions or concerns about these Terms, please
            contact us at <b>contact.danielamos@gmail.com</b>.
          </p>
        </div>
      </div>
    </div>
  );
};

export default TC;
